#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from codoxer
import codoxer
from codoxer.transformers import CxxTokenizer

if __name__ == '__main__':
    usage = 'code for which author is to be predicted'
    description = 'code'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser()
    parser.add_argument(description, help = usage)

    args = parser.parse_args()

    file = args.code


    # open file
    with open(file, 'r') as open_file:
        code = open_file.read()


    # Tokenize code
    tokenizer = CxxTokenizer()

    code_tokenized = tokenizer.fit_transform(code)
